"""Initial migration

Revision ID: 05ef8837fe1a
Revises: 19a61bf4d948
Create Date: 2024-09-11 23:53:02.728072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05ef8837fe1a'
down_revision = '19a61bf4d948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
