"""Initial migration

Revision ID: 19a61bf4d948
Revises: 5c9cee5abdd2
Create Date: 2024-09-11 23:36:13.360460

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19a61bf4d948'
down_revision = '5c9cee5abdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
