"""articles

Revision ID: 51b9e89f9cf7
Revises: 9e572fb8c322
Create Date: 2024-09-13 15:32:00.520726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51b9e89f9cf7'
down_revision = '9e572fb8c322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
