"""Initial migration

Revision ID: 5c9cee5abdd2
Revises: fcadb0ddb5a7
Create Date: 2024-09-11 23:25:09.333465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5c9cee5abdd2'
down_revision = 'fcadb0ddb5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
