"""Initial migration

Revision ID: 9e572fb8c322
Revises: 05ef8837fe1a
Create Date: 2024-09-12 12:11:10.978790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e572fb8c322'
down_revision = '05ef8837fe1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
