"""Initial migration

Revision ID: dd6f4d476dc4
Revises: 2c5f1003d9f4
Create Date: 2024-09-13 15:38:43.210645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd6f4d476dc4'
down_revision = '2c5f1003d9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
