"""Initial migration

Revision ID: fcadb0ddb5a7
Revises: 
Create Date: 2024-09-11 23:24:10.849651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcadb0ddb5a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.alter_column('avatar', 'key_words',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('avatar', 'domain',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('avatar', 'tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatar', 'tone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('avatar', 'domain',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('avatar', 'key_words',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('avatar', 'is_global')
    # ### end Alembic commands ###
